name: Run Tests

on: [push, pull_request]

jobs:
    run-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install PHP and extensions
              run: |
                  sudo apt update
                  sudo apt install -y software-properties-common
                  sudo add-apt-repository ppa:ondrej/php
                  sudo apt update
                  sudo apt -y install php php-curl php-xml php-mbstring php-mysql

            - name: Start MySQL
              run: |
                  sudo service mysql start
                  sudo mysql -e "CREATE DATABASE IF NOT EXISTS task_manager;"
                  sudo mysql -e "CREATE USER IF NOT EXISTS 'root'@'localhost' IDENTIFIED BY '';"
                  sudo mysql -e "GRANT ALL PRIVILEGES ON task_manager.* TO 'root'@'localhost';"
                  sudo mysql -e "FLUSH PRIVILEGES;"

            - name: Install Composer dependencies
              run: composer update

            - name: Run unit tests
              run: |
                  php artisan migrate
                  php artisan test
