name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Adjust PHP version if needed

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Set up database
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server
        sudo service mysql start

        mysql -e "CREATE DATABASE IF NOT EXISTS task_manager;"
        mysql -e "CREATE USER 'forge'@'localhost' IDENTIFIED BY 'password';"
        mysql -e "GRANT ALL PRIVILEGES ON task_manager.* TO 'forge'@'localhost';"
        mysql -e "FLUSH PRIVILEGES;"

    - name: Configure .env
      run: |
        cp .env.example .env
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=task_manager" >> .env
        echo "DB_USERNAME=forge" >> .env
        echo "DB_PASSWORD=password" >> .env

    - name: Check MySQL Status
      run: sudo service mysql status

    - name: Check MySQL Users
      run: mysql -e "SELECT user, host FROM mysql.user;"

    - name: Run migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: task_manager
        DB_USERNAME: forge
        DB_PASSWORD: password
      run: php artisan migrate --force

    - name: Run tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: task_manager
        DB_USERNAME: forge
        DB_PASSWORD: password
      run: php artisan test
