name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Adjust PHP version if needed

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Set up database
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server
        sudo service mysql start

        # Create database and user with no password
        mysql -e "CREATE DATABASE IF NOT EXISTS ${DB_DATABASE};"
        mysql -e "CREATE USER IF NOT EXISTS '${DB_USERNAME}'@'localhost';"
        mysql -e "GRANT ALL PRIVILEGES ON ${DB_DATABASE}.* TO '${DB_USERNAME}'@'localhost';"
        mysql -e "FLUSH PRIVILEGES;"

    - name: Run migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ''
      run: php artisan migrate --force

    - name: Run tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ''
      run: php artisan test
